export const uniformProjection = 'up'
export const uniformView = 'uv'
export const uniformModel = 'um'
export const uniformColor = 'uc'
export const uniformTextures = 'ut'
export const uniformCameraPosition = 'ucp'
export const uniformLife = 'ul'

export const attributePosition = 'ap'
export const attributeBrightness = 'ab'
export const attributeColor = 'ac'

export const varyingPosition = 'vp'
export const varyingColor = 'vc'
export const varyingDistance = 'vd'
