export const uniformProjection = 'up'
export const uniformView = 'uv'
export const uniformModel = 'um'
export const uniformColor = 'uc'
export const uniformTextures = 'ut'
export const uniformHeadPosition = 'uhp'
export const uniformCameraPosition = 'ucp'
export const uniformFocusPosition = 'ufp'
export const uniformKick = 'uk'
export const uniformSnare = 'us'
export const uniformTime = 'ui'

export const attributePosition = 'ap'
export const attributeParticleProperties = 'app'
export const attributeColor = 'ac'

export const varyingPosition = 'vp'
export const varyingUv = 'vu'
export const varyingColor = 'vc'
export const varyingDistance = 'vd'
